on: [push]

jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build and test ACT inside Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build act
        id: build_act
        uses: martinweismann/AutomaticComponentToolkit@rtti-native-2
        with:
          command: 'act'
      - name: run examples
        id: build_and_test_examples
        uses: martinweismann/AutomaticComponentToolkit@rtti-native-2
        with:
          command: 'examples'
